services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

  nominatim:
    image: mediagis/nominatim:4.0
    ports:
      - "8080:8080"
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/france-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/europe/france-updates
      - IMPORT_WIKIPEDIA=false
      - IMPORT_TIGER=false
    volumes:
      - nominatim_data:/var/lib/postgresql/14/main

volumes:
  postgres_data: 
  nominatim_data: 