version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: communes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/communes_db
    depends_on:
      - postgres
      
volumes:
  postgres_data: